The lecture notes claim that softmax is equivalent to sigmoid when n=2. He didn't prove or explain this further, so I thought I'd prove it here myself.


So obviously they're not equal, what am I doing wrong? 

The first thing to emphasize is that when they say n=2, they don't mean n datapoints, they mean n parameters. I.e. they are talking about $\theta$, not $X$.

So here's what I'm going to do: 

1. Prove the result algebraically 
2. Prove the result numerically

[This answer on Quora seems to explain stuff pretty well!](https://www.quora.com/Why-is-it-better-to-use-Softmax-function-than-sigmoid-function)

Here's the idea rewritten: 

Softmax definition: 

\begin{align}
P(y = k | X) = \frac{\exp({\theta_j^T \cdot X})}{\sum_{i=0}^{n-1}{\exp({\theta_i^T \cdot X})}} 
= \frac{1}{\sum_{i=0}^{n-1}{\exp({(\theta_i - \theta_j)^T \cdot X})}}
= \frac{1}{\sum_{i=0}^{n-1}{\exp(-{(\theta_j - \theta_i)^T \cdot X})}}
\end{align}


When n = 2,
\begin{align}
P(y = 1 | X) = \frac{1}{\sum_{i=0}^{n-1}{\exp(-{(\theta_1 - \theta_i)^T . X})}}
= \frac{1}{{\exp(-{(\theta_1 - \theta_0)^T . X})}} + \frac{1}{{\exp(-{(\theta_1 - \theta_1)^T . X})}}
= \frac{1}{{\exp(-{(\theta_1 - \theta_0)^T . X})} + 1}
= \sigma((\theta_1 - \theta_0)^T . X)
\end{align}




### Now to prove numerically 

In [1]:
import numpy as np 

In [2]:
num_data_points, num_features, num_classes = 1000, 10, 2

data_matrix = np.random.normal(size=(num_data_points, num_features))
weights_matrix = np.random.random(size=(num_features, num_classes - 1))

In [3]:
z = np.matmul(data_matrix, weights_matrix)
z[:10]

array([[ 2.00341915],
       [-3.37907801],
       [ 1.26428011],
       [-1.69648325],
       [-2.63148071],
       [-0.65286135],
       [ 1.41190924],
       [-0.13983102],
       [-1.1909293 ],
       [ 2.9465373 ]])

## Using sigmoid 

In [4]:
p = np.exp(z) / (1 + np.exp(z))
p[:10]

array([[0.8811556 ],
       [0.03295577],
       [0.77976203],
       [0.15492513],
       [0.06713965],
       [0.34234503],
       [0.80406691],
       [0.46509909],
       [0.23309277],
       [0.95009958]])

In [5]:
sigmoid_predictions = (p > 0.5).astype(int).reshape(1, -1)[0]

## Using softmax

In [6]:
matrix_for_softmax = np.hstack([1 - p, p])

In [7]:
softmax_predictions = matrix_for_softmax.argmax(axis=1)

## Comparing results

In [8]:
softmax_predictions[:10]

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 1])

In [9]:
sigmoid_predictions[:10]

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 1])

In [10]:
np.unique(softmax_predictions == sigmoid_predictions, return_counts=True)

(array([ True]), array([1000]))

### Just a reminder: 


By linear regression, we say: 

\begin{align}
f(y | X_i) = \sum_{j=0}^{n-1}{{\theta_j^T \cdot X_i}}
\end{align}

For linear regression, we say: 

\begin{align}
logit(P(y=k | X_i)) = \sum_{j=0}^{n-1}{{\theta_j^T \cdot X_i}}
\end{align}

Where: 

\begin{align}
logit(x) = \log\frac{p}{1-p}
\end{align}

So:

\begin{align}
P(y=k | X_i) = \frac{1}{1+\exp(-y)}
\end{align}

Where: 

\begin{align}
y = \exp{\sum_{j=0}^{n-1}{{\theta_j^T \cdot X_i}}}
\end{align}
